### ISSUE TITLE
配置文件中缺失database=和table=所对应的index和type的映射配置

### ISSUE THREAD

**Issue by dengdaisky520** [starcwang/canal_mysql_elasticsearch_sync#10]
求助，RT

**Comment by dengdaisky520** [comment]
请问index和type映射配置需要在哪里配置，谢谢

**Comment by starcwang** [comment]
在配置文件mapping.properties中，有配置数据库和表的映射关系，文档如下：https://github.com/starcwang/canal_mysql_elasticsearch_sync/wiki/QuickStart#42mappingproperties

**Comment by dengdaisky520** [comment]
万分谢谢，终于解决了
