### ISSUE TITLE
如何触发增量的数据导入es

### ISSUE THREAD

**Issue by huzekang** [starcwang/canal_mysql_elasticsearch_sync#11]
目前可以通过springboot启动访问开放的api进行全量导入到es，但是我在更改数据库数据后，发现没有同步到es，控制台也没反应

**Comment by starcwang** [comment]
@peter1040080742 你好，canal和本sync服务都部署好，并且配置文件配置好后，增量同步默认就是开启的，读下文档，检查下各个服务是否正常，配置文件是否正确~
