### ISSUE TITLE
调用syncByTable接口时，如果数据库中只有一条字段不会触发同步操作

### ISSUE THREAD

**Issue by TooYoungTooSimples** [starcwang/canal_mysql_elasticsearch_sync#12]
![image](https://user-images.githubusercontent.com/33820442/53078497-4b9fa700-352f-11e9-822b-d5144561d598.png)

这里的条件应该用do while语句来防止第一次的时候数据为一条时不触发同步操作，因为查询出来的MinId跟MaxId是同一个值。

**Comment by starcwang** [comment]
@TooYoungTooSimples  感谢反馈，已经在1.0.5版本修复
