### ISSUE TITLE
数据为0000-00-00 字段类型DATETIME 报错问题

### ISSUE THREAD

**Issue by phpyandong** [starcwang/canal_mysql_elasticsearch_sync#7]
数据库中的这个数据，同步时会报错。

**Comment by jnliao** [comment]
可以先确定一下你数据库字段格式和es中数据格式是否一致

**Comment by starcwang** [comment]
你好，phpyandong，原因是在做日期转换的时候，使用java8的LocalDateTime类型，不存在的日期会报错（0000-00-00），建议默认值换个历史上存在的日子。☺
